### ISSUE TITLE
AUCC code: how do you break ties with wilcox data

### ISSUE THREAD

**Issue by kalanir** [neurorestore/DE-analysis#11]
Looking at the "functions/calculate_overlap.R" code, it seems that a 'test_statistic' column is not assigned within the wilcox output and I don't see any such column in the FindMarkers wilcox dataframes. How did you break ties in the AUCC analysis when comparing wilcox results because I've noticed some of the genes can have the same pvalue assigned (0s and 1s)?

**Comment by skinnider** [comment]
This is addressed in the Methods

> We observed that some statistical tests returned a large number of p-values below the double precision limit in R (approximately 2 × 10–308), potentially confounding the calculation of the concordance metrics described below. To avoid this pitfall, we modified the Seurat implementation to also return the value of the test statistic from which the p-value was derived. The modified version of Seurat 3.1.5 used to perform all single-cell DE analyses reported in this study is available from http://github.com/jordansquair/Seurat.
